# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CookBook' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CookBook
  platform :ios, '9.0'
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Database', '~>5.3.0'
  pod 'Firebase/Auth', '~> 5.3.0'
  pod 'Firebase/Storage', '~> 5.3.0'

  target 'CookBookTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CookBook-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CookBook-tvOS

  target 'CookBook-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
